name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.platform == 'windows-latest'
        name: Conditionally install pytorch
        run: pip3 install torch -f https://download.pytorch.org/whl/torch_stable.html
      - id: measurement-4
        name: Record Measurement After Conditionally install pytorch
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Conditionally install pytorch
          task: get-measurement
      - name: Install locally
        run: "python -m pip install --upgrade pip

          git submodule update --init --recursive

          python -m pip install .

          "
      - id: measurement-6
        name: Record Measurement After Install locally
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install locally
          task: get-measurement
      - name: Check installation
        run: python $GITHUB_WORKSPACE/scripts/check_installation.py
        working-directory: /tmp
      - id: measurement-8
        name: Record Measurement After Check installation
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check installation
          task: get-measurement
      - name: Install optional test requirements
        run: "python -m pip install '.[dev,docs]'

          python -m pip install iopath transformers pyarrow

          python -m pip install git+https://github.com/facebookresearch/fairscale.git@main

          python -m pip install pygit2 pgzip

          "
      - id: measurement-10
        name: Record Measurement After Install optional test requirements
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install optional test requirements
          task: get-measurement
      - if: matrix.platform == 'macos-latest'
        name: Install xformers for Macos
        run: "brew install llvm libomp

          CC=/usr/local/opt/llvm/bin/clang CXX=clang++ pip install git+https://github.com/facebookresearch/xformers.git@main

          "
      - id: measurement-12
        name: Record Measurement After Install xformers for Macos
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install xformers for Macos
          task: get-measurement
      - if: matrix.platform != 'macos-latest'
        name: Install xformers for non-MacOS
        run:
          "python -m pip install --progress-bar off git+https://github.com/facebookresearch/xformers.git@main

          "
      - id: measurement-14
        name: Record Measurement After Install xformers for non-MacOS
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install xformers for non-MacOS
          task: get-measurement
      - name: Lint with black
        run: black --check --diff .
      - id: measurement-16
        name: Record Measurement After Lint with black
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Lint with black
          task: get-measurement
      - name: Lint with flake8
        run:
          "# stop the build if there are Python syntax errors or undefined names

          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars
          wide

          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          "
      - id: measurement-18
        name: Record Measurement After Lint with flake8
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Lint with flake8
          task: get-measurement
      - name: Build doc
        run: make singlehtml
        working-directory: docs/
      - id: measurement-20
        name: Record Measurement After Build doc
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build doc
          task: get-measurement
      - name: Run tests
        run: pytest --import-mode=append -vvv tests/
      - id: measurement-22
        name: Record Measurement After Run tests
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${ steps.final-measurement.outputs.data-total-json }' > total_energy_consumption-1740225204.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-1740225204.json
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        python-version:
          - 3.8
          - 3.9
      max-parallel: 4
